# Variables
EXE= bw ubw

# Usual compilation flags
CFLAGS= -std=c99 -Wall -Wextra -g
CPPFLAGS= -I../include
# Special rules and targets
.PHONY: all clean help

# Rules and targets
all: $(EXE)

bw: bw.c lbw.c lbw.h
	$(CC) $^ $(CFLAGS) $(CPPFLAGS) -o $@

ubw: u_bw.c lbw.c lbw.h
	$(CC) $^ $(CFLAGS) $(CPPFLAGS) -o $@ 

clean:
	@rm -f *.o file *.bw $(EXE)

help:
	@echo "Usage:"
	@echo "  make [all]\t\tBuild"
	@echo "  make clean\t\tRemove all files generated by make"
	@echo "  make help\t\tDisplay this help"
