# Variables
EXE= bw ubw

# Usual compilation flags
CFLAGS= -std=c99 -Wall -Wextra -g
CPPFLAGS= -I../include

# Special rules and targets
.PHONY: all clean help

# Rules and targets
all: $(EXE) ubw

ubw: u_bw.c
	$(CC) u_bw.c $(CFLAGS) $(CPPFLAGS) -o ubw

clean:
	@rm -f *.o $(EXE)

help:
	@echo "Usage:"
	@echo "  make [all]\t\tBuild"
	@echo "  make clean\t\tRemove all files generated by make"
	@echo "  make help\t\tDisplay this help"
